# Generated by Django 3.1.6 on 2021-02-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
    ]
