# Generated by Django 3.1.6 on 2021-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crack', '0002_remove_contact_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
